In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import sys
import os

In [12]:
df = pd.read_csv('/Users/cynthiagao/PycharmProjects/IDX Exchange Internship/IDX Files/CRMLSListing/CRMLSListing_Master_Residential.csv', low_memory=False)

In [13]:
df.describe()

,OriginalListPrice,ListingKey,ClosePrice,Latitude,Longitude,LivingArea,ListPrice,DaysOnMarket,FireplacesTotal,AboveGradeFinishedArea,...,Latitude.1,ListPrice.1,CoveredSpaces,Stories,LotSizeArea,MainLevelBedrooms,GarageSpaces,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict
count,5.400320e+05,5.408040e+05,1.421060e+05,460637.000000,460637.000000,5.402490e+05,5.408040e+05,540804.000000,0.0,0.0,...,460637.000000,5.408040e+05,0.0,446186.000000,4.970410e+05,294008.000000,510736.000000,410763.000000,4.968660e+05,0.0
mean,1.397617e+06,1.104852e+09,1.202351e+06,34.604746,-118.462020,1.979958e+03,1.313748e+06,19.239608,NaN,NaN,...,34.604746,1.313748e+06,NaN,1.371036,4.777701e+04,2.046876,1.844837,270.990404,4.129317e+05,NaN
std,7.353427e+06,2.990728e+07,4.342096e+06,1.998928,3.554453,2.336924e+04,2.346993e+06,26.665932,NaN,NaN,...,1.998928,2.346993e+06,NaN,0.483083,2.257161e+06,6.438713,3.876514,2368.397088,2.082770e+07,NaN
min,0.000000e+00,1.018357e+09,5.250000e+02,-117.472493,-159.475987,0.000000e+00,1.000000e+02,-58.000000,NaN,NaN,...,-117.472493,1.000000e+02,NaN,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,NaN
25%,5.850000e+05,1.077383e+09,6.000000e+05,33.739990,-118.689395,1.247000e+03,5.800000e+05,5.000000,NaN,NaN,...,33.739990,5.800000e+05,NaN,1.000000,5.000000e+03,1.000000,1.000000,0.000000,5.227000e+03,NaN
50%,8.490000e+05,1.105017e+09,8.517125e+05,34.053544,-118.028347,1.668000e+03,8.449900e+05,11.000000,NaN,NaN,...,34.053544,8.449900e+05,NaN,1.000000,7.194000e+03,2.000000,2.000000,125.000000,7.405000e+03,NaN
75%,1.389000e+06,1.126986e+09,1.350000e+06,34.476455,-117.237528,2.300000e+03,1.375000e+06,22.000000,NaN,NaN,...,34.476455,1.375000e+06,NaN,2.000000,1.205100e+04,3.000000,2.000000,400.000000,1.360875e+04,NaN
max,1.390000e+09,1.156831e+09,8.200000e+08,737.000000,329.000000,1.702132e+07,1.950000e+08,731.000000,NaN,NaN,...,737.000000,1.950000e+08,NaN,2.000000,9.187423e+08,3333.000000,600.000000,968348.000000,7.638115e+09,NaN

In [14]:
df.shape

(540804, 84)

In [15]:
df.info

<bound method DataFrame.info of         OriginalListPrice  ListingKey                        ListAgentEmail  \
0               1340000.0  1074973329                    haleh360@Gmail.com
1               2500000.0  1074954552  Reneechen@yourhomesoldguaranteed.com
2               3150000.0  1074936537                      anader@dppre.com
3               3090000.0  1074917818                  QIANYU0607@GMAIL.COM
4              12725000.0  1074143166          jeff.williams@pacificsir.com
...                   ...         ...                                   ...
540799          5750000.0  1151417547                                   NaN
540800           475000.0  1150815309                                   NaN
540801           825000.0  1148377048                                   NaN
540802          2849000.0  1145743715                                   NaN
540803          1649000.0  1139631172                                   NaN

       CloseDate  ClosePrice ListAgentFirstName ListAgentLastName   Latitude  \
0            NaN         NaN              Haleh       Dowlatshahi  34.052207
1            NaN         NaN              Renee              Chen  33.496363
2            NaN         NaN           Margaret             Nader  34.119345
3            NaN         NaN             QIANYU              GUAN  33.984057
4            NaN         NaN               Jeff          Williams  33.607583
...          ...         ...                ...               ...        ...
540799       NaN         NaN           Jennifer           Okhovat  34.080126
540800       NaN         NaN            Melissa             Sofia  32.801681
540801       NaN         NaN            Adriana             Gliha  32.621759
540802       NaN         NaN               Lori           Barnett  33.102975
540803       NaN         NaN             George          Wood Jr.  32.579821

         Longitude                UnparsedAddress  ... MainLevelBedrooms  \
0      -118.408445  2220 Avenue Of The Stars 2704  ...               NaN
1      -117.691677                   16 Palisades  ...               0.0
2      -118.111254              1615 Waverly Road  ...               NaN
3      -117.802819         2250 Indian Creek Road  ...               1.0
4      -117.887743                317 E. Bayfront  ...               3.0
...            ...                            ...  ...               ...
540799 -118.383738            8732 Rangely Avenue  ...               NaN
540800 -117.237403         4600 lamont street 226  ...               1.0
540801 -116.996024         1461 Fieldbrook Street  ...               0.0
540802 -117.299101          1005 Canvasback Drive  ...               1.0
540803 -117.104163             943 Georgia Street  ...               NaN

        NewConstructionYN  GarageSpaces     HighSchoolDistrict PostalCode  \
0                   False           NaN                    NaN      90067
1                   False           3.0     Capistrano Unified      92677
2                     NaN           2.0                    NaN      91108
3                   False           4.0  Walnut Valley Unified      91765
4                   False           2.0   Newport Mesa Unified      92662
...                   ...           ...                    ...        ...
540799              False           NaN                    NaN      90048
540800              False           1.0      San Diego Unified      92109
540801                NaN           2.0       Sweetwater Union      91913
540802                NaN           3.0       Carlsbad Unified      92011
540803                NaN           0.0       Sweetwater Union      91932

       BuyerOfficeName.1 AssociationFee LotSizeSquareFeet  \
0                    NaN        2105.00          177861.0
1                    NaN         254.00            5300.0
2                    NaN            NaN            9404.0
3                    NaN         295.95           58232.0
4                    NaN           0.00            2250.0
...                  ...            ...               ...
540799               NaN            NaN            5093.0
540800               NaN         802.00          428219.0
540801               NaN         116.00            3049.2
540802               NaN         227.00           12645.0
540803               NaN           0.00            7191.0

       MiddleOrJuniorSchoolDistrict              UnparsedAddress.1
0                               NaN  2220 Avenue Of The Stars 2704
1                               NaN                   16 Palisades
2                               NaN              1615 Waverly Road
3                               NaN         2250 Indian Creek Road
4                               NaN                317 E. Bayfront
...                             ...                            ...
540799                          NaN            8732 Rangely Avenue
540800                          NaN         4600 lamont street 226
540801                          NaN         1461 Fieldbrook Street
540802                          NaN          1005 Canvasback Drive
540803                          NaN             943 Georgia Street

[540804 rows x 84 columns]>

In [16]:
df.dtypes

OriginalListPrice               float64
ListingKey                        int64
ListAgentEmail                      str
CloseDate                           str
ClosePrice                      float64
                                 ...
BuyerOfficeName.1                   str
AssociationFee                  float64
LotSizeSquareFeet               float64
MiddleOrJuniorSchoolDistrict    float64
UnparsedAddress.1                   str
Length: 84, dtype: object

In [17]:
# Drop duplicate columns

duplicate_cols = [col for col in df.columns if col.endswith('.1')]
df = df.drop(columns=duplicate_cols)

df.shape

(540804, 73)

In [18]:
# Drop columns where more than 90% of values are unique strings

# Exclude date columns
date_cols = ["ListingContractDate", "CloseDate", "PurchaseContractDate", "ContractStatusChangeDate"]

high_cardinality = [
    col for col in df.columns
    if col not in date_cols and df[col].nunique() / len(df) > 0.9
]

print(f"Suggested columns to drop: {high_cardinality}")

df = df.drop(columns=high_cardinality)

df.shape

Suggested columns to drop: ['ListingKey', 'ListingKeyNumeric', 'ListingId']

(540804, 70)

In [19]:
# Drop columns that have more than 50% NaN

cols_more_than_50_nan = [
    col for col in df.columns
    if col not in date_cols and df[col].isna().mean() > 0.5
]

print("Columns with more than 50% missing values:")
print(cols_more_than_50_nan)

# Drop those columns
df = df.drop(columns=cols_more_than_50_nan)

df.shape

Columns with more than 50% missing values:
['ClosePrice', 'BuyerOfficeName', 'CoListOfficeName', 'CoListAgentFirstName', 'CoListAgentLastName', 'BuyerAgentMlsId', 'BuyerAgentFirstName', 'BuyerAgentLastName', 'FireplacesTotal', 'AssociationFeeFrequency', 'AboveGradeFinishedArea', 'TaxAnnualAmount', 'ElementarySchool', 'BuilderName', 'SubdivisionName', 'BuyerOfficeAOR', 'BuyerAgencyCompensationType', 'BuyerAgencyCompensation', 'TaxYear', 'BuildingAreaTotal', 'ElementarySchoolDistrict', 'CoBuyerAgentFirstName', 'BelowGradeFinishedArea', 'BusinessType', 'CoveredSpaces', 'MiddleOrJuniorSchool', 'HighSchool', 'LotSizeDimensions', 'MiddleOrJuniorSchoolDistrict']

(540804, 41)

In [20]:
df.head()

,OriginalListPrice,ListAgentEmail,CloseDate,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,PropertyType,LivingArea,...,Stories,Levels,LotSizeArea,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet
0,1340000.0,haleh360@Gmail.com,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,Residential,1301.0,...,1.0,One,177861.0,NaN,False,NaN,NaN,90067,2105.00,177861.0
1,2500000.0,Reneechen@yourhomesoldguaranteed.com,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,Residential,2788.0,...,2.0,Two,5300.0,0.0,False,3.0,Capistrano Unified,92677,254.00,5300.0
2,3150000.0,anader@dppre.com,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,Residential,3250.0,...,2.0,Two,9404.0,NaN,NaN,2.0,NaN,91108,NaN,9404.0
3,3090000.0,QIANYU0607@GMAIL.COM,NaN,QIANYU,GUAN,33.984057,-117.802819,2250 Indian Creek Road,Residential,7456.0,...,NaN,ThreeOrMore,58232.0,1.0,False,4.0,Walnut Valley Unified,91765,295.95,58232.0
4,12725000.0,jeff.williams@pacificsir.com,NaN,Jeff,Williams,33.607583,-117.887743,317 E. Bayfront,Residential,2321.0,...,NaN,ThreeOrMore,2250.0,3.0,False,2.0,Newport Mesa Unified,92662,0.00,2250.0

Market Analysis Fields = columns that help you analyze the real estate market

Metadata Fields = columns that mainly describe the record, system, import process, or listing identity, but do not help much with market insights

In [21]:
# Identify Market Analysis Fields

analysis_fields = ['OriginalListPrice', 'LivingArea', 'ListPrice', 'DaysOnMarket', 'AttachedGarageYN', 'ParkingTotal', 'LotSizeAcres', 'YearBuilt', 'BathroomsTotalInteger', 'BedroomsTotal', 'FireplaceYN', 'Stories', 'Levels', 'LotSizeArea', 'MainLevelBedrooms', 'NewConstructionYN', 'GarageSpaces','LotSizeSquareFeet']

target_col = []

In [22]:
# Change YN columns to 0/1 Binary variables, with NaN = 0

YN_columns = ['NewConstructionYN', 'FireplaceYN', 'AttachedGarageYN']

for col in YN_columns:
    df[col] = (
        df[col]
        .replace({"Yes": 1, "No": 0})
        .fillna(0)
        .astype(int)
    )

df.head()

,OriginalListPrice,ListAgentEmail,CloseDate,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,PropertyType,LivingArea,...,Stories,Levels,LotSizeArea,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet
0,1340000.0,haleh360@Gmail.com,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,Residential,1301.0,...,1.0,One,177861.0,NaN,0,NaN,NaN,90067,2105.00,177861.0
1,2500000.0,Reneechen@yourhomesoldguaranteed.com,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,Residential,2788.0,...,2.0,Two,5300.0,0.0,0,3.0,Capistrano Unified,92677,254.00,5300.0
2,3150000.0,anader@dppre.com,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,Residential,3250.0,...,2.0,Two,9404.0,NaN,0,2.0,NaN,91108,NaN,9404.0
3,3090000.0,QIANYU0607@GMAIL.COM,NaN,QIANYU,GUAN,33.984057,-117.802819,2250 Indian Creek Road,Residential,7456.0,...,NaN,ThreeOrMore,58232.0,1.0,0,4.0,Walnut Valley Unified,91765,295.95,58232.0
4,12725000.0,jeff.williams@pacificsir.com,NaN,Jeff,Williams,33.607583,-117.887743,317 E. Bayfront,Residential,2321.0,...,NaN,ThreeOrMore,2250.0,3.0,0,2.0,Newport Mesa Unified,92662,0.00,2250.0

In [23]:
# Create year/month features from date columns

df['ListingContractDate'] = pd.to_datetime(df['ListingContractDate'], errors='coerce')
df['list_year'] = df['ListingContractDate'].dt.year
df['list_month'] = df['ListingContractDate'].dt.month
df['list_yrmo'] = df['list_year'] * 100 + df['list_month']

print("Listings date range:", df['ListingContractDate'].min().date(), "to", df['ListingContractDate'].max().date())

Listings date range: 2024-01-01 to 2026-03-31

In [24]:
df.head()

,OriginalListPrice,ListAgentEmail,CloseDate,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,PropertyType,LivingArea,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,list_year,list_month,list_yrmo
0,1340000.0,haleh360@Gmail.com,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,Residential,1301.0,...,NaN,0,NaN,NaN,90067,2105.00,177861.0,2024,1,202401
1,2500000.0,Reneechen@yourhomesoldguaranteed.com,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,Residential,2788.0,...,0.0,0,3.0,Capistrano Unified,92677,254.00,5300.0,2024,1,202401
2,3150000.0,anader@dppre.com,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,Residential,3250.0,...,NaN,0,2.0,NaN,91108,NaN,9404.0,2024,1,202401
3,3090000.0,QIANYU0607@GMAIL.COM,NaN,QIANYU,GUAN,33.984057,-117.802819,2250 Indian Creek Road,Residential,7456.0,...,1.0,0,4.0,Walnut Valley Unified,91765,295.95,58232.0,2024,1,202401
4,12725000.0,jeff.williams@pacificsir.com,NaN,Jeff,Williams,33.607583,-117.887743,317 E. Bayfront,Residential,2321.0,...,3.0,0,2.0,Newport Mesa Unified,92662,0.00,2250.0,2024,1,202401

In [28]:
import sys
sys.path.append("/Users/cynthiagao/PycharmProjects/IDX Exchange Internship/IDX Files/functions")

from data_cleaning_functions import missing_value_report

list_missing = missing_value_report(df, "New Listings")

=== New Listings: 31 columns with missing values ===
                          Missing Count  Missing %
CloseDate                        378094      69.91
PurchaseContractDate             276064      51.05
MainLevelBedrooms                246796      45.64
HighSchoolDistrict               162726      30.09
AssociationFee                   130041      24.05
Stories                           94618      17.50
Latitude                          80167      14.82
Longitude                         80167      14.82
MLSAreaMajor                      73152      13.53
Levels                            58382      10.80
ListAgentEmail                    47622       8.81
LotSizeAcres                      44602       8.25
LotSizeSquareFeet                 43938       8.12
LotSizeArea                       43763       8.09
GarageSpaces                      30068       5.56
ContractStatusChangeDate           6106       1.13
ListAgentFirstName                 4241       0.78
PropertySubType                    1253       0.23
YearBuilt                           933       0.17
StreetNumberNumeric                 860       0.16
OriginalListPrice                   772       0.14
UnparsedAddress                     680       0.13
City                                575       0.11
LivingArea                          555       0.10
BedroomsTotal                       148       0.03
ListAgentFullName                    91       0.02
StateOrProvince                      53       0.01
BathroomsTotalInteger                55       0.01
ListAgentLastName                    40       0.01
ParkingTotal                         20       0.00
PostalCode                           13       0.00

In [29]:
from plots_functions import (
    plot_missing_values, plot_boxplots, plot_sold_distributions,
    plot_listing_distributions, plot_monthly_kpi_trends, plot_yoy_comparison,
    plot_supply_vs_demand, plot_top_counties, plot_top_cities,
    plot_subtype_comparison, plot_price_vs_size, plot_dom_bucket_analysis,
    plot_price_reductions, plot_top_offices, plot_top_agents,
    plot_correlation_heatmap, plot_close_vs_list, plot_price_tiers,
    plot_new_construction
)

plot_missing_values(list_missing)

TypeError: plot_missing_values() missing 1 required positional argument: 'list_missing'